title: Tyrant
author: Vin
email: hahahahaah
description: > # this means to ignore newlines until "baseurl:"
a place to type code

# social links
twitter_username: intriguedpenguin
github_username:  bahhhh

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
